#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NAV_ID_NDB       2
#define NAV_ID_VOR       3
#define NAV_ID_LOC       4
#define NAV_ID_LOC_ALONE 5
#define NAV_ID_GS        6
#define NAV_ID_OM        7
#define NAV_ID_MM        8
#define NAV_ID_IM        9
#define NAV_ID_DME       12
#define NAV_ID_DME_ALONE 13
#define NAV_ID_GBAS_FINAL 14
#define NAV_ID_GBAS_GS    15
#define NAV_ID_GBAS_LAND  16

#define NAV_CIFP_TYPE_IF 1
#define NAV_CIFP_TYPE_TF 2
#define NAV_CIFP_TYPE_CF 3
#define NAV_CIFP_TYPE_DF 4
#define NAV_CIFP_TYPE_FA 5
#define NAV_CIFP_TYPE_FC 6
#define NAV_CIFP_TYPE_FD 7
#define NAV_CIFP_TYPE_FM 8
#define NAV_CIFP_TYPE_CA 9
#define NAV_CIFP_TYPE_CD 10
#define NAV_CIFP_TYPE_CI 11
#define NAV_CIFP_TYPE_CR 12
#define NAV_CIFP_TYPE_RF 13
#define NAV_CIFP_TYPE_AF 14
#define NAV_CIFP_TYPE_VA 15
#define NAV_CIFP_TYPE_VD 16
#define NAV_CIFP_TYPE_VI 17
#define NAV_CIFP_TYPE_VM 18
#define NAV_CIFP_TYPE_VR 19
#define NAV_CIFP_TYPE_PI 20
#define NAV_CIFP_TYPE_HA 21
#define NAV_CIFP_TYPE_HF 22
#define NAV_CIFP_TYPE_HM 23


#define NAV_CIFP_CSTR_ALT_NONE 0
#define NAV_CIFP_CSTR_ALT_ABOVE 1
#define NAV_CIFP_CSTR_ALT_BELOW 2
#define NAV_CIFP_CSTR_ALT_AT 3
#define NAV_CIFP_CSTR_ALT_ABOVE_BELOW 4
#define NAV_CIFP_CSTR_ALT_ABOVE_2ND 5
#define NAV_CIFP_CSTR_ALT_GLIDE 6

#define NAV_CIFP_CSTR_SPD_NONE 0
#define NAV_CIFP_CSTR_SPD_ABOVE 1
#define NAV_CIFP_CSTR_SPD_BELOW 2
#define NAV_CIFP_CSTR_SPD_AT 3
#endif // CONSTANTS_H
